// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDtP8pzjDNzGGJF2yfaCiSo7sx6JYFMSw',
    appId: '1:777332670415:web:4147ff882fa78a105f1cba',
    messagingSenderId: '777332670415',
    projectId: 'what-s-up-332e4',
    authDomain: 'what-s-up-332e4.firebaseapp.com',
    storageBucket: 'what-s-up-332e4.appspot.com',
    measurementId: 'G-V86T0MT40N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFAP_Dvt_jDQmCIKai6_EfR3IKwJWQRcQ',
    appId: '1:777332670415:android:8af36ae0bd309e365f1cba',
    messagingSenderId: '777332670415',
    projectId: 'what-s-up-332e4',
    storageBucket: 'what-s-up-332e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcz-OZFXIa9o3DF5LHYagmXppXOFShhi0',
    appId: '1:777332670415:ios:ffe871bb5e48fa455f1cba',
    messagingSenderId: '777332670415',
    projectId: 'what-s-up-332e4',
    storageBucket: 'what-s-up-332e4.appspot.com',
    iosClientId: '777332670415-cgqqiq4h2jgtslop87hsc85v1d071oak.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcz-OZFXIa9o3DF5LHYagmXppXOFShhi0',
    appId: '1:777332670415:ios:ffe871bb5e48fa455f1cba',
    messagingSenderId: '777332670415',
    projectId: 'what-s-up-332e4',
    storageBucket: 'what-s-up-332e4.appspot.com',
    iosClientId: '777332670415-cgqqiq4h2jgtslop87hsc85v1d071oak.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsUp',
  );
}
